name: Deploy via FTP

on:
  push:
    branches:
      - develop

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files via FTP
        uses: bradley-codes/ftp-deploy@v1.0.0
        with:
          ftp-server: ftp://dataon.com.br
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-directory: dist/dataon-web-utils/browser
          server-directory: /
