name: Deploy via FTP

on:
  push:
    branches:
      - develop

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files via FTP
        uses: sebastianpopp/ftp-action@v1.3.0
        with:
          server: ftp://dataon.com.br
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/dataon-web-utils/browser
          server-dir: /
